import './globals.css'
import Link from "next/link";
import LogoutButton from "@/components/LogoutButton";
import {createServerComponentClient} from "@supabase/auth-helpers-nextjs";
import {Database} from "@/database.types";
import {cookies} from "next/headers";
import {HomeIcon, RocketLaunchIcon} from "@heroicons/react/20/solid";

export const metadata = {
    title: 'Create Next App', description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {

    return (<html lang="en">
    <body>

    <main className="min-h-screen bg-background flex flex-col p-4">
        {children}
    </main>
    </body>
    </html>)
}
