import './globals.css'
import Link from "next/link";
import LogoutButton from "@/components/LogoutButton";
import {createServerComponentClient} from "@supabase/auth-helpers-nextjs";
import {Database} from "@/database.types";
import {cookies} from "next/headers";
import {HomeIcon, RocketLaunchIcon} from "@heroicons/react/20/solid";

export const metadata = {
    title: 'Create Next App', description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    const supabase = createServerComponentClient<Database>({cookies})

    const {
        data: {user},
    } = await supabase.auth.getUser()

    return (<html lang="en">
    <body>
    <nav className="w-full flex border-b border-b-foreground/10 h-16">
        <div className="w-full flex justify-between  items-center p-3 text-sm text-foreground">
            <div className={"flex gap-8"}>
            <Link className="flex items-center" href="/"><HomeIcon className={"w-6 text-primary"}/>Home</Link>
            <Link className="flex items-center" href="/admin/attributes"><RocketLaunchIcon className={"w-6 text-primary"}/>Admin</Link>
            </div>

            {user ? (<div className="flex items-center gap-4">
                <LogoutButton/>
            </div>) : (<Link
                href="/login"
                className="py-2 px-4 rounded-md no-underline bg-btn-background hover:bg-btn-background-hover"
            >
                Login
            </Link>)}
        </div>
    </nav>
    <main className="min-h-screen bg-background flex flex-col p-4">
        {children}
    </main>
    </body>
    </html>)
}
